version: '3.9'

services:
  proxy:
    # basic proxy; proxy should run only once for all projects
    image: jwilder/nginx-proxy
    container_name: nginx-proxy-proxy-1
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true
