name: PHP Code Sniffer

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Composer install
        uses: php-actions/composer@v6
				with:
					php_version: 8.2
					working_dir: wp-content/themes/wi-starter-fse

      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 8.2
          path: wp-content/themes/wi-starter-fse
          standard: WordPress
