name: PHP Code Sniffer

on: [push]

jobs:
  code-sniffer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: php-actions/composer@v6
	      with:
	        php_version: 8.2
	        working_dir: wp-content/themes/wi-starter-fse

      - uses: php-actions/phpcs@v1
        with:
          php_version: 8.2
          path: wp-content/themes/wi-starter-fse
          standard: WordPress
