name: WPCS check

on: pull_request

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: WPCS check
          uses: 10up/wpcs-action@stable
          with:
            standard: 'WordPress'
            paths: 'wp-content/themes/wi-starter-fse'
            use_local_config: 'true'
